firstname=Mohamed
lastname=Sulaiman
email=test@example.com
room=Family Room (1 to 4 People)
people=2
arrivalDate=04-17-2026
arrivalTime=05:20
ampm=AM
flight=AI-202
requests=Late check-in
depMonth=April
depDay=20
depYear=2026
arrivalMonth=April
arrivalDay=17
arrivalYear=2026